services:
  todoop_backend:
    build: .
    ports:
      - "3500:3500"
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    env_file:
      - .env
    command: npm run dev
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:latest
    command: mongod --auth
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env

volumes:
  mongo_data:
  node_modules:
